### ISSUE TITLE
Can't get moonraker reporter working.

### ISSUE THREAD

**Issue by gogocat** [LateRoomsGroup/moonraker#34] opened 2016-03-15 11:21 UTC
Hi, 

Am I doing something wrong? mocha seems not able to reference 'moonraker' reporter.

project root: D:\tmp\moonraker\config.json

Errors:
D:\tmp\moonraker\node_modules\mocha\lib\mocha.js:149
   if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
                   ^

Error: invalid reporter "../../../lib/reporter"
   at Mocha.reporter (D:\tmp\moonraker\node_modules\mocha\lib\mocha.js:149:27)

**Comment by Paul2e** [comment] 2016-03-16 12:58
Hi @gogocat 

I've been unable to reproduce this issue, and the response is coming back from within Mocha.

I've got a couple of suggestions for you to try, and it would be good if you can feedback?

1. Can you check that your config.json has the following line:

 ` "reporter": "moonraker",'

If not please update. 

2. Delete the node_modules from your moonraker folder, and reinstall with npm.

If you are still having issues, can you paste your config.json file into here? Removing any parts which are sensitive. 

Thanks

Paul

**Comment by gogocat** [comment] 2016-03-17 14:18
Hi Paul,

Thanks for your help, this is config i use.
{
  "baseUrl": "http://www.gumtree.com.au/",
  "featuresDir": "tests/features",
  "stepsDir": "tests/steps",
  "resultsDir": "results",

  "threads": 1,

  "testTimeout": 60000,
  "elementTimeout": 5000,

  "tags": "!@wip",

  "browser": {
    "browserName": "chrome",
    "chromeOptions": {
      "args": ["--no-sandbox"]
    }
  }
}

Looks like mocha couldn't find the reporter location?
I using Windows and my directory looks like this:
D:/tmp/moonraker
                |----node_modules
                |----results
                |----tests
                |----config.json
                |----package.son

Adam

**Comment by gogocat** [comment] 2016-03-29 13:07
I got it working by modifying \node_modules\moonraker\lib\env\mocha.js
using path.resolve to let it workout current directory and cross platform issue.
...
var moonrakerReporter = path.resolve(__dirname, '../reporter');
var reporter = (config.reporter === 'moonraker') ? moonrakerReporter : config.reporter;
...

**Comment by Paul2e** [comment] 2016-03-29 14:01
Nice to hear you got it working, but it's very strange how you needed to modify code within a thirdparty npm module to get it running. 

I think the root cause is within your config and project structure, but not been able to narrow it down yet. Will keep you updated.

**Comment by karlatkinson** [comment] 2017-01-04 13:43
This should be fixed in 0.4.0

**Closed by karlatkinson** 2017-01-04 13:43 UTC
